AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  SketchApp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sketch-app/
      Handler: index.handler
      Environment:
        Variables:
          SKETCH_TABLE: !Ref SketchTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SketchTable
      Events:
        SketchApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        SketchRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

  AiAssistFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./test/
      Handler: ai-assist-handler.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      Events:
        AiAssistApi:
          Type: Api
          Properties:
            Path: /ai-assist
            Method: POST
        AiAssistOptions:
          Type: Api
          Properties:
            Path: /ai-assist
            Method: OPTIONS

  SketchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-sketches"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sketchId
          AttributeType: S
      KeySchema:
        - AttributeName: sketchId
          KeyType: HASH

Outputs:
  SketchApi:
    Description: "API Gateway endpoint URL for Sketch App"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SketchFunction:
    Description: "Sketch Lambda Function ARN"
    Value: !GetAtt SketchApp.Arn
