AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Resources:
  SketchApp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sketch-app/
      Handler: index.handler
      Environment:
        Variables:
          SKETCH_TABLE: !Ref SketchTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SketchTable
      Events:
        SketchApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        SketchRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

  AiAssist:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ai-assist/
      Handler: index.handler
      Runtime: nodejs22.x
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AI_MODE: dev
      Events:
        AiAssistApi:
          Type: Api
          Properties:
            Path: /ai-assist
            Method: POST

  SketchUtils:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./sketch-utils/
      Handler: index.handler
      Runtime: nodejs22.x
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          SKETCHES_TABLE: !Ref SketchTable
          MODE: dev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SketchTable
      Events:
        SaveSketchApi:
          Type: Api
          Properties:
            Path: /save-sketch
            Method: POST
        GetSketchesApi:
          Type: Api
          Properties:
            Path: /get-sketches
            Method: GET
        SetSketchPublicApi:
          Type: Api
          Properties:
            Path: /set-sketch-public
            Method: POST

  SketchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-sketches-v2
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: N
        - AttributeName: sketchId
          AttributeType: S
        - AttributeName: isPublic
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: sketchId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: PublicSketches
          KeySchema:
            - AttributeName: isPublic
              KeyType: HASH
            - AttributeName: sketchId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  GitHubOAuth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./github-oauth/
      Handler: index.handler
      Runtime: nodejs22.x
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          GITHUB_CLIENT_ID: !Ref GitHubClientId
          GITHUB_CLIENT_SECRET: !Ref GitHubClientSecret
      Events:
        GitHubOAuthApi:
          Type: Api
          Properties:
            Path: /auth/github
            Method: POST

Parameters:
  GitHubClientId:
    Type: String
    Description: GitHub OAuth App Client ID
    Default: Ov23liNUvc7QG2vvoSfM
  GitHubClientSecret:
    Type: String
    Description: GitHub OAuth App Client Secret
    NoEcho: true

Outputs:
  SketchApi:
    Description: API Gateway endpoint URL for Sketch App
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  SketchFunction:
    Description: Sketch Lambda Function ARN
    Value: !GetAtt SketchApp.Arn